### ISSUE TITLE
Team details ✌✌

### ISSUE THREAD

**Issue by CarlosE-Feliz** [Hope1226/ruby-items-library#18]
### Hello there! In this case, we are working on **Ruby capstone**

To check our project click here [Kanban board](https://github.com/Hope1226/ruby-items-library/projects/1)

### Team members:
Team members are listed below with the same number they have for tasks.

1. @Hope1226 
2. @nicupop729 
3. @CarlosE-Feliz 

_Feel free to leave us any suggestions or changes! Cheers!!😎_

<img src="https://media0.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif"/>

**Comment by BrianSammit** [comment]
# STATUS: APPROVED :green_circle: :clap: 

Hello @Hope1226, @CarlosE-Feliz,  and @nicupop729 , 
Your project is complete!  There is nothing else to say other than... Great job 👏 
Congratulations! 🎉 

TO HIGHLIGHT:

-  Great job setting up the Kanban board 
- You did an amazing job giving a fair amount of work to every person on your team 

Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
